[package]

name = "tclscan"
version = "0.0.1"
authors = ["Aidan Hobson Sayers <aidanhs@cantab.net>"]

[dependencies.rust-bindgen]
git = "https://github.com/danburkert/rust-bindgen.git"
branch = "master"

[[bin]]

name = "tclscan"
